# Form implementation generated from reading ui file 'Login2.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(480, 581)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 480, 540))
        self.label_4.setAutoFillBackground(True)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("pngtree-cafe-promotion-poster-background-image_145807.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 10, 360, 120))
        self.label_5.setStyleSheet("background-color:rgb(126, 110, 109);\n"
"font: 48pt \"Vladimir Script\";\n"
"border-radius: 10px;\n"
"border: 5px soild #000000;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.users = QtWidgets.QLineEdit(self.centralwidget)
        self.users.setGeometry(QtCore.QRect(100, 180, 280, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.users.setFont(font)
        self.users.setStyleSheet("background:rgb(255, 219, 167);\n"
"border-radius: 10px;\n"
"Border:None;")
        self.users.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.users.setObjectName("users")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(100, 280, 280, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setStyleSheet("background:rgb(255, 219, 167);\n"
"border-radius: 10px;\n"
"Border:None;")
        self.password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password.setObjectName("password")
        self.usuario_incorrecto = QtWidgets.QLabel(self.centralwidget)
        self.usuario_incorrecto.setGeometry(QtCore.QRect(150, 220, 180, 30))
        self.usuario_incorrecto.setStyleSheet("background-color: rgba(0, 0, 0 , 0%);\n"
"font: 10pt \"Arial\";\n"
"color:rgb(255, 0, 0);\n"
"border:none;")
        self.usuario_incorrecto.setText("")
        self.usuario_incorrecto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.usuario_incorrecto.setObjectName("usuario_incorrecto")
        self.contrasena_incorrecta = QtWidgets.QLabel(self.centralwidget)
        self.contrasena_incorrecta.setGeometry(QtCore.QRect(160, 320, 171, 51))
        self.contrasena_incorrecta.setStyleSheet("background-color: rgba(0, 0, 0 , 0%);\n"
"font: 10pt \"Arial\";\n"
"color:rgb(255, 0, 0);\n"
"border:none;")
        self.contrasena_incorrecta.setText("")
        self.contrasena_incorrecta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.contrasena_incorrecta.setObjectName("contrasena_incorrecta")
        self.bt_ingresar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_ingresar.setGeometry(QtCore.QRect(195, 370, 90, 30))
        self.bt_ingresar.setStyleSheet("QPushButton{\n"
"    \n"
"        background-color:rgb(126, 110, 109);\n"
"        font: 8pt \"MS Shell Dlg 2\";\n"
"        color:rgb(255, 255, 255);\n"
"        border-radius: 15px;\n"
"border:1px soild #00007f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"        background-color:rgb(67, 42, 37);\n"
"        font: 8pt \"MS Shell Dlg 2\";\n"
"        border-radius: 15px;\n"
"border:1px soild #00007f;\n"
"\n"
"}\n"
"")
        self.bt_ingresar.setObjectName("bt_ingresar")
        self.salir = QtWidgets.QPushButton(self.centralwidget)
        self.salir.setGeometry(QtCore.QRect(195, 480, 80, 30))
        self.salir.setStyleSheet("QPushButton{\n"
"    \n"
"        background-color:rgba(0, 0, 0, 0%);\n"
"        font: 8pt \"MS Shell Dlg 2\";\n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"        background-color:rgb(121, 73, 9) ;\n"
"        font: 8pt \"MS Shell Dlg 2\";\n"
"        border-radius: 0px;\n"
"\n"
"}")
        self.salir.setObjectName("salir")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 140, 160, 40))
        self.label_6.setStyleSheet("background-color: rgba(0, 0, 0 , 0%);\n"
"font: 12pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 240, 160, 40))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0 , 0%);\n"
"font: 12pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.label_5.setText(_translate("Login", "Iniciar Sesión"))
        self.users.setPlaceholderText(_translate("Login", "Ingrese su usuario"))
        self.password.setPlaceholderText(_translate("Login", "Ingrese su su contraseña"))
        self.bt_ingresar.setText(_translate("Login", "Continuar"))
        self.salir.setText(_translate("Login", "Salir"))
        self.label_6.setText(_translate("Login", "Usuario"))
        self.label_3.setText(_translate("Login", "Contraseña"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
